#!/bin/bash
npm install --prefix ./ProblemB/server
npm install --prefix ./ProblemB/front
npm install --prefix ./ProblemA/solution
npm install nodemon -g

npm start --prefix ./ProblemB/server &
npm run dev --prefix ./ProblemB/front &
npm run dev --prefix ./ProblemA/solution
